version: "{build}"
configuration: Release
image: Visual Studio 2017
install:
  - ps: choco install gitversion.portable -pre -y -r
before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver
build:
  verbosity: minimal
after_build:
  - dotnet msbuild /t:Restore,Pack /p:PackageOutputPath=.\artifacts
artifacts:
  - path: artifacts\**\*.*