version: "{build}"
configuration: Release
image: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
  - ps: choco install gitversion.portable -pre -y -r --no-progress
before_build:
  - dotnet restore
  - ps: gitversion /output buildserver /updateAssemblyInfo
build_script:
  - dotnet build
test_script:
  - ps: pushd src\\Oxide.Tests; dotnet xunit --fx-version=2.0.5; popd
after_build:
  - dotnet msbuild /t:Restore,Pack /p:PackageOutputPath=artifacts /p:Version="%GitVersion_NuGetVersion%"
artifacts:
  - path: "**\\artifacts\\**\\*.*"